//Esercizio pag. 389 n. 8.20
#include <stdio.h>
#include <string.h>

int main() {
    char string[] = "'A Livella\n"
                    "La livella è le escroveto che l'usa il muratore per nivelari il muro, dunque\n"
                    "Ogn'anno, il due novembre, c'é l'usanza\n"
                    "Per i defunti andare al Cimitero\n"
                    "Ognuno ll'adda fà chesta crianza\n"
                    "Ognuno adda tené chistu penziero\n"
                    "Ogn'anno, puntualmente, in questo giorno\n"
                    "Di questa triste e mesta ricorrenza\n"
                    "Anch'io ci vado, e con dei fiori adorno\n"
                    "Il loculo marmoreo 'e zi' Vicenza\n"
                    "St'anno m'é capitato 'navventura\n"
                    "Dopo di aver compiuto il triste omaggio\n"
                    "Madonna, si ce penzo, e che paura!\n"
                    "Ma po' facette un'anema e curaggio\n"
                    "'O fatto è chisto, statemi a sentire\n"
                    "S'avvicinava ll'ora d'à chiusura\n"
                    "Io, tomo tomo, stavo per uscire\n"
                    "Buttando un occhio a qualche sepoltura\n"
                    "\"Qui dorme in pace il nobile marchese\n"
                    "Signore di Rovigo e di Belluno\n"
                    "Ardimentoso eroe di mille imprese\n"
                    "Morto l'11 maggio del'31\"\n"
                    "'O stemma cu 'a curona 'ncoppa a tutto\n"
                    "Sotto 'na croce fatta 'e lampadine\n"
                    "Tre mazze 'e rose cu 'na lista 'e lutto\n"
                    "Cannele, cannelotte e sei lumine\n"
                    "Proprio azzeccata 'a tomba 'e stu signore\n"
                    "Nce stava 'n 'ata tomba piccerella\n"
                    "Abbandunata, senza manco un fiore\n"
                    "Pe' segno, sulamente 'na crucella\n"
                    "E ncoppa 'a croce appena se liggeva:\n"
                    "\"Esposito Gennaro - netturbino\"\n"
                    "Guardannola, che ppena me faceva\n"
                    "Stu muorto senza manco nu lumino\n"
                    "Questa è la vita! 'ncapo a me penzavo\n"
                    "Chi ha avuto tanto e chi nun ave niente\n"
                    "Stu povero maronna s'aspettava\n"
                    "Ca pur all'atu munno era pezzente?\n"
                    "Mentre fantasticavo stu penziero\n"
                    "S'era ggià fatta quase mezanotte\n"
                    "E i'rimanette 'nchiuso priggiuniero\n"
                    "Muorto 'e paura... nnanze 'e cannelotte\n"
                    "Tutto a 'nu tratto, che veco 'a luntano?\n"
                    "Ddoje ombre avvicenarse 'a parte mia\n"
                    "Penzaje: stu fatto a me mme pare strano\n"
                    "Stongo scetato... dormo, o è fantasia?\n"
                    "Ate che fantasia; era 'o Marchese\n"
                    "C'o' tubbo, 'a caramella e c'o' pastrano\n"
                    "Chill'ato apriesso a isso un brutto arnese\n"
                    "Tutto fetente e cu 'nascopa mmano\n"
                    "E chillo certamente è don Gennaro\n"
                    "'Omuorto puveriello' o scupatore\n"
                    "'Int 'a stu fatto i' nun ce veco chiaro\n"
                    "So' muorte e se ritirano a chest'ora?\n"
                    "Putevano sta' 'a me quase 'nu palmo\n"
                    "Quanno 'o Marchese se fermaje 'e botto\n"
                    "S'avota e tomo, tomo, calmo, calmo\n"
                    "Dicette a don Gennaro: \"Giovanotto!\"\n"
                    "Da Voi vorrei saper, vile carogna\n"
                    "Con quale ardire e come avete osato\n"
                    "Di farvi seppellir, per mia vergogna\n"
                    "Accanto a me che sono blasonato!\n"
                    "La casta è casta e va, si, rispettata,\n"
                    "Ma Voi perdeste il senso e la misura\n"
                    "La Vostra salma andava, si, inumata\n"
                    "Ma seppellita nella spazzatura\n"
                    "Ancora oltre sopportar non posso\n"
                    "La Vostra vicinanza puzzolente\n"
                    "Fa d'uopo, quindi, che cerchiate un fosso\n"
                    "Tra i vostri pari, tra la vostra gente\n"
                    "\"Signor Marchese, nun è colpa mia\n"
                    "I'nun v'avesse fatto chistu tuorto\n"
                    "Mia moglie è stata a ffa' sta fesseria\n"
                    "I' che putevo fa' si ero muorto?\n"
                    "Si fosse vivo ve farrei cuntento\n"
                    "Pigliasse 'a casciulella cu 'e qquatt'osse\n"
                    "E proprio mo, obbj'...'nd'a stu mumento\n"
                    "Mme ne trasesse dinto a n'ata fossa\"\n"
                    "\"E cosa aspetti, oh turpe malcreato\n"
                    "Che l'ira mia raggiunga l'eccedenza?\n"
                    "Se io non fossi stato un titolato\n"
                    "Avrei già dato piglio alla violenza!\"\n"
                    "\"Famme vedé.-piglia sta violenza\n"
                    "'A verità, Marché, mme so' scucciato\n"
                    "'E te senti; e si perdo 'a pacienza\n"
                    "Mme scordo ca so' muorto e so mazzate!\n"
                    "Ma chi te cride d'essere, nu ddio?\n"
                    "Ccà dinto, 'o vvuo capi, ca simmo eguale?\n"
                    "Muorto si'tu e muorto so' pur'io;\n"
                    "Ognuno comme a 'na'ato é tale e quale\"\n"
                    "\"Lurido porco! Come ti permetti\n"
                    "Paragonarti a me ch'ebbi natali\n"
                    "Illustri, nobilissimi e perfetti\n"
                    "Da fare invidia a Principi Reali?\"\n"
                    "\"Tu qua' Natale, Pasca e Ppifania\n"
                    "T\"o vvuo' mettere 'ncapo' int'a cervella\n"
                    "Che staje malato ancora è fantasia?\n"
                    "'A morte 'o ssaje ched\"e? è una livella.\n"
                    "'Nu rre, 'nu maggistrato, 'nu grand'ommo\n"
                    "Trasenno stu canciello ha fatt'o punto\n"
                    "C'ha perzo tutto, 'a vita e pure 'o nomme\n"
                    "Tu nu t'hè fatto ancora chistu cunto?\n"
                    "Perciò, stamme a ssenti, nun fa\"o restivo\n"
                    "Suppuorteme vicino-che te 'mporta?\n"
                    "Sti ppagliacciate 'e ffanno sulo 'e vive\n"
                    "Nuje simmo serie, appartenimmo à morte!\"";

    int cont = 0;
    char *token = strtok(string," \n");

    while (token != NULL) {
        cont++;
        token = strtok(NULL," \n");
    }

    printf("Le parole nella frase sono: %d",cont);
    return 0;
}

